export const portfolioData = [
  {
    "id": 1,
    "imageUrl": "content/img/portfolio/qards.svg",
    "altText": "QaRds App business cards for a digital future",
    "title": "QaRds",
    "name": "QaRds",
    "description": "Application that creates digital business cards for account users, using node for authentication and mysql to store the data.",
    "siteUrl": "https://business-qard.herokuapp.com/",
    "siteAria": "View the QaRds portfolio website",
    "repoUrl": "https://github.com/jondam1985/business-QaRd",
    "repoAria": "View the QaRds github repository",
  },
  {
    "id": 2,
    "imageUrl": "content/img/portfolio/neighbourhood-3.svg",
    "altText": "Toronto Neighbourhood Safety app",
    "title": "Is My Neighbourhood Safe?",
    "name": "Is My Neighbourhood Safe?",
    "description": "Application that compares crime data by neighbourhood for all of Toronto from 2014 forward, built with HTML, CSS & JS.",
    "siteUrl": "https://andydurette.github.io/UFT-Project-1/",
    "siteAria": "View Toronto Neighbourhood safety portfolio website",
    "repoUrl": "https://github.com/andydurette/UFT-Project-1",
    "repoAria": "View Toronto Neighbourhood safety github repository",
  },
  {
    "id": 3,
    "imageUrl": "content/img/portfolio/g-book.svg",
    "altText": "Google Books",
    "title": "Google Books",
    "name": "MERN Stack Google Books",
    "description": "Application built using the MERN Stack, created to add and remove google books api data from a database.",
    "siteUrl": "https://react-google-books-application.herokuapp.com/",
    "siteAria": "MERN Stack Google Books website",
    "repoUrl": "https://github.com/andydurette/Google-Books-Search",
    "repoAria": "MERN Stack Google Books repository",
  },
  {
    "id": 4,
    "imageUrl": "content/img/portfolio/weather.svg",
    "altText": "Toronto weather json data api site",
    "title": "React.js Weather App",
    "name": "React.js Weather App",
    "description": "Application where I utilized the openweather API, React.js, and Netlify to host a service to check the weather.",
    "siteUrl": "https://openweather-react.netlify.com/",
    "siteAria": "View React.js Weather App portfolio website",
    "repoUrl": "https://github.com/andydurette/openweather-react",
    "repoAria": "View React.js Weather App portfolio repo",
  },
  {
    "id": 5,
    "imageUrl": "content/img/portfolio/team-profile.svg",
    "altText": "Team Profile App",
    "title": "Team Profile App",
    "name": "Team Profile App",
    "description": "Node CLI Application built to handle requests to generate a team site from provided command line input.",
    "siteUrl": "",
    "siteAria": "View Team Profile App",
    "repoUrl": "https://github.com/andydurette/team-profile-generator",
    "repoAria": "View the Team Profile App repository",
  },
  {
    "id": 6,
    "imageUrl": "content/img/portfolio/employee-tracker.svg",
    "altText": "Employee tracker app",
    "title": "Employee tracker",
    "name": "Employee tracker",
    "description": "Node CLI Application built to update a mySQL database of employee info viewing, adding, and removing data.",
    "siteUrl": "",
    "siteAria": "View Employee tracker app",
    "repoUrl": "https://github.com/andydurette/Employee-Tracker",
    "repoAria": "View Employee tracker app",
  },
  {
    "id": 7,
    "imageUrl": "content/img/portfolio/pass-gen.svg",
    "altText": "Password Generator app",
    "title": "Password Generator app",
    "name": "Password Generator",
    "description": "Small Application where you can generate a password based off you own choice of requirements to be met.",
    "siteUrl": "https://andydurette.github.io/password-generator",
    "siteAria": "View password generator website",
    "repoUrl": "https://github.com/andydurette/password-generator",
    "repoAria": "View password-generator github repository",
  },
  {
    "id": 8,
    "imageUrl": "content/img/portfolio/30-days.svg",
    "altText": "30 day icon challenge",
    "title": "Password Generator app",
    "name": "30 day icon challenge",
    "description": "A project where I designed an icon a day for a month in order to better produce vector graphics quickly and efficently.",
    "siteUrl": "https://icon-gallery.netlify.com/",
    "siteAria": "View 30 Day Icon Challenge portfolio website",
    "repoUrl": "https://github.com/andydurette/icon-gallery",
    "repoAria": "View 30 Day Icon Challenge portfolio repo",
  },
  {
    "id":9,
    "imageUrl": "content/img/portfolio/bee.svg",
    "altText": "Bees of America",
    "title": "Bees of America",
    "name": "Bees of America",
    "description": "A project where I researched the history of bees and utilized React.js, github and Netlify to host a react routed app.",
    "siteUrl": "https://bees-react.netlify.com/",
    "siteAria": "View Bees of America portfolio website",
    "repoUrl": "https://github.com/andydurette/Bees",
    "repoAria": "View Bees of America portfolio website",
  }
]




