// All tags in capitals to make checking easier

export const portfolioData = [
  {
    "id":"1",
    "imageUrl": "content/img/portfolio/turnnout.svg",
    "altText": "Turrnout",
    "title": "Turrnout",
    "name": "Turrnout",
    "description": "Built using AWS AppSync Turnnout is a video on demand subscription service offering of dance classes.",
    "siteUrl": "https://www.turnnout.com/",
    "siteAria": "Built using AWS AppSync Turnnout is a video on demand subscription service offering of dance classes.",
    "repoUrl": "",
    "repoAria": "",
    "tags" : ["HTML5", "CSS3", "JAVASCRIPT", "REACT", "NODE", "CI/CD", "LINT", "DEVOPS", "FULL STACK", "AWS APPSYNC", "REDUX TOOLKIT", "GRAPHQL"],
    "filter" : ["HTML5", "CSS3", "JAVASCRIPT", "REACT", "NODE", "CI/CD", "LINT", "DEVOPS", "FULL STACK", "AWS APPSYNC", "REDUX TOOLKIT", "GRAPHQL"],
  },
  {
    "id": "2",
    "imageUrl": "content/img/portfolio/neighbourhood-3.svg",
    "altText": "Toronto Neighbourhood Safety app",
    "title": "Is My Neighbourhood Safe?",
    "name": "Is My Neighbourhood Safe?",
    "description": "Application that compares crime data by neighbourhood for all of Toronto from 2014 forward, built with HTML, CSS & JS.",
    "siteUrl": "https://toronto-neighbourhood-safety.herokuapp.com/",
    "siteAria": "View Toronto Neighbourhood safety portfolio website",
    "repoUrl": "https://github.com/andydurette/Toronto-Neighborhood-Safety",
    "repoAria": "View Toronto Neighbourhood safety github repository",
    "tags" : ["HTML5", "CSS3", "JAVASCRIPT", "NODE", "EXPRESS", "SASS", "FULL STACK"],
    "filter" : ["HTML5", "CSS3", "JAVASCRIPT", "NODE", "EXPRESS", "SASS", "FULL STACK"],
  },
  {
    "id": "3",
    "imageUrl": "content/img/portfolio/g-book.svg",
    "altText": "Google Books",
    "title": "Google Books",
    "name": "MERN Stack Google Books",
    "description": "Application built using the MERN Stack, created to add and remove google books api data from a database.",
    "siteUrl": "https://react-google-books-application.herokuapp.com/",
    "siteAria": "MERN Stack Google Books website",
    "repoUrl": "https://github.com/andydurette/Google-Books-Search",
    "repoAria": "MERN Stack Google Books repository",
    "tags" : ["HTML5", "CSS3", "JAVASCRIPT", "NODE", "EXPRESS", "MERN", "MONGODB", "REACT", "SASS", "FULL STACK"],
    "filter" : ["HTML5", "CSS3", "JAVASCRIPT", "NODE", "EXPRESS", "MERN", "MONGODB", "REACT", "SASS", "FULL STACK"],
  },
  {
    "id": "4",
    "imageUrl": "content/img/portfolio/qards.svg",
    "altText": "QaRds App business cards for a digital future",
    "title": "QaRds",
    "name": "QaRds",
    "description": "Application that creates digital business cards for account users, using node for authentication and mysql to store data.",
    "siteUrl": "https://business-qard.herokuapp.com/",
    "siteAria": "View the QaRds portfolio website",
    "repoUrl": "https://github.com/jondam1985/business-QaRd",
    "repoAria": "View the QaRds github repository",
    "tags" : ["HTML5", "CSS3", "JAVASCRIPT", "NODE", "EXPRESS", "MYSQL", "SASS", "FULL STACK"],
    "filter" : ["HTML5", "CSS3", "JAVASCRIPT", "NODE", "EXPRESS", "MYSQL", "SASS", "FULL STACK"],
  },
  {
    "id":"5",
    "imageUrl": "content/img/portfolio/nextfantasy.svg",
    "altText": "Next Fantasy",
    "title": "Next Fantasy",
    "name": "Next Fantasy",
    "description": "Tabletop fantasy site built utilizing next.js dynamic routing, as well as devops practices such as CI/CD pipeline.",
    "siteUrl": "https://nextfantasy.herokuapp.com/",
    "siteAria": "Next Fantasy live website",
    "repoUrl": "https://github.com/andydurette/nextfantasy",
    "repoAria": "Next Fantasy github portfolio",
    "tags" : ["HTML5", "CSS3", "JAVASCRIPT", "REACT", "NODE", "NEXTJS", "JEST", "SASS", "CI/CD", "LINT", "DEVOPS", "FULL STACK", "FIREBASE"],
    "filter" : ["HTML5", "CSS3", "JAVASCRIPT", "REACT", "NODE", "NEXTJS", "JEST", "SASS", "CI/CD", "LINT", "DEVOPS", "FULL STACK", "FIREBASE"],
  },
  {
    "id": "6",
    "imageUrl": "content/img/portfolio/30-days.svg",
    "altText": "30 day icon challenge",
    "title": "Password Generator app",
    "name": "30 day icon challenge",
    "description": "A project where I designed an icon a day for a month in order to better produce vector graphics quickly and efficently.",
    "siteUrl": "https://icon-gallery.netlify.com/",
    "siteAria": "View 30 Day Icon Challenge portfolio website",
    "repoUrl": "https://github.com/andydurette/icon-gallery",
    "repoAria": "View 30 Day Icon Challenge portfolio repo",
    "tags" : ["HTML5", "CSS3", "JAVASCRIPT", "REACT", "ILLUSTRATOR", "UI/UX", "FRONT END"],
    "filter" : ["HTML5", "CSS3", "JAVASCRIPT", "REACT", "ILLUSTRATOR", "UI/UX", "FRONT END"],
  },
  {
    "id":"7",
    "imageUrl": "content/img/portfolio/bee.svg",
    "altText": "Bees of America",
    "title": "Bees of America",
    "name": "Bees of America",
    "description": "A project where I researched the history of bees and utilized React.js, github and Netlify to host a react routed app.",
    "siteUrl": "https://bees-react.netlify.com/",
    "siteAria": "View Bees of America portfolio website",
    "repoUrl": "https://github.com/andydurette/Bees",
    "repoAria": "View Bees of America portfolio website",
    "tags" : ["HTML5", "CSS3", "JAVASCRIPT", "REACT", "ILLUSTRATOR", "SASS", "FRONT END"],
    "filter" : ["HTML5", "CSS3", "JAVASCRIPT", "REACT", "ILLUSTRATOR", "SASS", "FRONT END"],
  },
  {
    "id": "8",
    "imageUrl": "content/img/portfolio/team-profile.svg",
    "altText": "Team Profile App",
    "title": "Team Profile App",
    "name": "Team Profile App",
    "description": "Node CLI Application built to handle requests to generate a team site from provided command line input.",
    "siteUrl": "",
    "siteAria": "",
    "repoUrl": "https://github.com/andydurette/team-profile-generator",
    "repoAria": "View the Team Profile App repository",
    "tags" : ["HTML5", "CSS3", "JAVASCRIPT", "NODE", "EXPRESS", "BACK END"],
    "filter" : ["HTML5", "CSS3", "JAVASCRIPT", "NODE", "EXPRESS", "BACK END"],
  },
  {
    "id": "9",
    "imageUrl": "content/img/portfolio/employee-tracker.svg",
    "altText": "Employee tracker app",
    "title": "Employee tracker",
    "name": "Employee tracker",
    "description": "Node CLI Application built to update a mySQL database of employee info viewing, adding, and removing data.",
    "siteUrl": "",
    "siteAria": "View Employee tracker app",
    "repoUrl": "https://github.com/andydurette/Employee-Tracker",
    "repoAria": "View Employee tracker app",
    "tags" : ["JAVASCRIPT", "NODE", "EXPRESS", "MYSQL", "BACK END"],
    "filter" : ["JAVASCRIPT", "NODE", "EXPRESS", "MYSQL", "BACK END"],
  },
  
]



// {
//   "id": "5",
//   "imageUrl": "content/img/portfolio/weather.svg",
//   "altText": "Toronto weather json data api site",
//   "title": "React.js Weather App",
//   "name": "React.js Weather App",
//   "description": "Application where I utilized the openweather API, React.js, and Netlify to host a service to check the weather.",
//   "siteUrl": "https://openweather-react.netlify.com/",
//   "siteAria": "View React.js Weather App portfolio website",
//   "repoUrl": "https://github.com/andydurette/openweather-react",
//   "repoAria": "View React.js Weather App portfolio repo",
//   "tags" : ["HTML5", "CSS3", "JAVASCRIPT", "REACT", "FRONT END"],
//   "filter" : ["HTML5", "CSS3", "JAVASCRIPT", "REACT", "FRONT END"],
// },
// {
//   "id": "7",
//   "imageUrl": "content/img/portfolio/pass-gen.svg",
//   "altText": "Password Generator app",
//   "title": "Password Generator app",
//   "name": "Password Generator",
//   "description": "Small Application where you can generate a password based off you own choice of requirements to be met.",
//   "siteUrl": "https://andydurette.github.io/password-generator",
//   "siteAria": "View password generator website",
//   "repoUrl": "https://github.com/andydurette/password-generator",
//   "repoAria": "View password-generator github repository",
//   "tags" : ["HTML5", "CSS3", "JAVASCRIPT", "FRONT END"],
//   "filter" : ["HTML5", "CSS3", "JAVASCRIPT", "FRONT END"],
// },