export const portfolioData = [
  {
    "id": 1,
    "imageUrl": "content/img/portfolio/qards.svg",
    "altText": "QaRds App business cards for a digital future",
    "title": "QaRds",
    "name": "QaRds",
    "description": "Application built in my University of Toronto Fullstack course, it creates digital business cards for account users.",
    "siteUrl": "https://business-qard.herokuapp.com/",
    "siteAria": "View the QaRds portfolio website",
    "repoUrl": "https://business-qard.herokuapp.com/",
    "repoAria": "View the QaRds github repository",
  },
  {
    "id": 2,
    "imageUrl": "content/img/portfolio/neighbourhood.svg",
    "altText": "Toronto Neighbourhood Safety app",
    "title": "Is My Neighbourhood Safe?",
    "name": "Is My Neighbourhood Safe?",
    "description": "Application built in my University of Toronto Fullstack course, it compares crime data by neighbourhood for all of Toronto.",
    "siteUrl": "https://andydurette.github.io/UFT-Project-1/",
    "siteAria": "View Toronto Neighbourhood safety portfolio website",
    "repoUrl": "https://github.com/andydurette/UFT-Project-1",
    "repoAria": "View Toronto Neighbourhood safety github repository",
  },
  {
    "id": 3,
    "imageUrl": "content/img/portfolio/weather.svg",
    "altText": "Toronto weather json data api site",
    "title": "React.js Weather App",
    "name": "React.js Weather App",
    "description": "A personal project where I worked with openweather API, React.js, and Netlify to host a weather application.",
    "siteUrl": "https://openweather-react.netlify.com/",
    "siteAria": "View React.js Weather App portfolio website",
    "repoUrl": "https://github.com/andydurette/openweather-react",
    "repoAria": "View React.js Weather App portfolio repo",
  },
  {
    "id": 4,
    "imageUrl": "content/img/portfolio/fit.svg",
    "altText": "code quiz",
    "title": "code quiz",
    "name": "Fitness Tracker",
    "description": "Application built in my University of Toronto Fullstack course, using a mongo database and node for crud operations.",
    "siteUrl": "https://workout-tracking.herokuapp.com",
    "siteAria": "View code quiz website",
    "repoUrl": "https://github.com/andydurette/Workout-Tracker",
    "repoAria": "View code quiz github repository",
  },
  {
    "id": 5,
    "imageUrl": "content/img/portfolio/team-profile.svg",
    "altText": "Team Profile App",
    "title": "Team Profile App",
    "name": "Team Profile App",
    "description": "Node CLI Application built in my University of Toronto Fullstack course, app handles requests to build a team site.",
    "siteUrl": "",
    "siteAria": "View Team Profile App",
    "repoUrl": "https://github.com/andydurette/team-profile-generator",
    "repoAria": "View the Team Profile App repository",
  },
  {
    "id": 6,
    "imageUrl": "content/img/portfolio/employee-tracker.svg",
    "altText": "Employee tracker app",
    "title": "Employee tracker",
    "name": "Employee tracker",
    "description": "Node CLI Application built in my University of Toronto Fullstack course, updates a mySQL database of employee info.",
    "siteUrl": "",
    "siteAria": "View Employee tracker app",
    "repoUrl": "https://github.com/andydurette/Employee-Tracker",
    "repoAria": "View Employee tracker app",
  },
  {
    "id": 7,
    "imageUrl": "content/img/portfolio/pass-gen.svg",
    "altText": "Password Generator app",
    "title": "Password Generator app",
    "name": "Password Generator",
    "description": "Small Application where you can generate a password based off you own choice of requirements to be met.",
    "siteUrl": "https://andydurette.github.io/password-generator",
    "siteAria": "View password generator website",
    "repoUrl": "https://github.com/andydurette/password-generator",
    "repoAria": "View password-generator github repository",
  },
  {
    "id": 8,
    "imageUrl": "content/img/portfolio/30-days.svg",
    "altText": "30 day icon challenge",
    "title": "Password Generator app",
    "name": "30 day icon challenge",
    "description": "A project where I designed an icon a day for a month in order to better produce vector graphics quickly and efficently.",
    "siteUrl": "https://icon-gallery.netlify.com/",
    "siteAria": "View 30 Day Icon Challenge portfolio website",
    "repoUrl": "https://github.com/andydurette/icon-gallery",
    "repoAria": "View 30 Day Icon Challenge portfolio repo",
  },
  {
    "id":9,
    "imageUrl": "content/img/portfolio/bee.svg",
    "altText": "Bees of America",
    "title": "Bees of America",
    "name": "Bees of America",
    "description": "A project where I researched the history of bees and utilized React.js, github and Netlify to host a react routed app.",
    "siteUrl": "https://bees-react.netlify.com/",
    "siteAria": "View Bees of America portfolio website",
    "repoUrl": "https://github.com/andydurette/Bees",
    "repoAria": "View Bees of America portfolio website",
  }
]




